# Generated by Django 3.2.5 on 2021-07-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'utilisateur")),
                ('prenom', models.CharField(max_length=50, verbose_name="Prenom de l'utilisateur")),
                ('genre', models.CharField(max_length=50, verbose_name="Genre de l'utilisateur")),
                ('telephone', models.CharField(max_length=50, verbose_name="Téléphone de l'utilisateur")),
                ('mot_de_passe', models.CharField(max_length=50, verbose_name="Mot de passe de l'utilisateur")),
            ],
        ),
    ]
